In [1]:
import pandas as pd
import sqlite3

# Creating, reading and writing

In [3]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [4]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [5]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [6]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [6]:
wine_reviews = pd.read_csv("winemag-data-130k-v2.csv", index_col=0)

In [9]:
wine_reviews.shape

(129971, 13)

In [10]:
wine_reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [3]:
conn = sqlite3.connect("FPA_FOD_20170508.sqlite")

In [4]:
fires = pd.read_sql_query("SELECT * FROM fires", conn)

In [7]:
wine_reviews.head().to_csv("wine_reviews.csv")

In [8]:
conn = sqlite3.connect("fires.sqlite")
fires.head(10).to_sql("fires", conn)

# Indexing, Selecting & Assigning

In [2]:
reviews = pd.read_csv("winemag-data-130k-v2.csv", index_col=0)
pd.set_option("display.max_rows", 5)
reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [4]:
reviews['country']

0            Italy
1         Portugal
            ...
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [5]:
reviews['country'][0]

'Italy'

In [6]:
reviews.iloc[0]

country                                                    Italy
description    Aromas include tropical fruit, broom, brimston...
                                     ...
variety                                              White Blend
winery                                                   Nicosia
Name: 0, Length: 13, dtype: object

In [7]:
reviews.iloc[:, 0]

0            Italy
1         Portugal
            ...
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [8]:
reviews.iloc[:3, 0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

In [9]:
reviews.iloc[1:3, 0]

1    Portugal
2          US
Name: country, dtype: object

In [10]:
reviews.iloc[[0, 1, 2], 0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

In [11]:
reviews.iloc[-5:]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [14]:
reviews.loc[0, 'country']

'Italy'

In [15]:
reviews.loc[:, ['taster_name', 'taster_twitter_handle', 'points']]

          taster_name taster_twitter_handle  points
0       Kerin O’Keefe          @kerinokeefe      87
1          Roger Voss            @vossroger      87
...               ...                   ...     ...
129969     Roger Voss            @vossroger      90
129970     Roger Voss            @vossroger      90

[129971 rows x 3 columns]

In [16]:
reviews.set_index("title")

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
title,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...
Domaine Marcel Deiss 2012 Pinot Gris (Alsace),France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Pinot Gris,Domaine Marcel Deiss
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace),France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Schoffit

In [17]:
reviews.country == 'Italy'

0          True
1         False
          ...
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

In [18]:
reviews.loc[reviews.country == 'Italy']

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

In [19]:
reviews.loc[(reviews.country == 'Italy') & (reviews.points >= 90)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
130,Italy,"At the first it was quite muted and subdued, b...",Bricco Rocche Brunate,91,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Brunate (Barolo),Nebbiolo,Ceretto
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

In [20]:
reviews.loc[(reviews.country == 'Italy') | (reviews.points >= 90)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [3]:
reviews.loc[reviews.country.isin(['Italy', 'France'])]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [4]:
reviews.loc[reviews.price.notnull()]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [5]:
reviews['critic'] = 'everyone'
reviews['critic']

0         everyone
1         everyone
            ...
129969    everyone
129970    everyone
Name: critic, Length: 129971, dtype: object

In [8]:
reviews['index_backwards'] = range(len(reviews), 0, -1)
reviews['index_backwards']

0         129971
1         129970
           ...
129969         2
129970         1
Name: index_backwards, Length: 129971, dtype: int64

# Summary Functions & Maps

In [11]:
reviews.points.describe()

count    129971.000000
mean         88.447138
             ...
75%          91.000000
max         100.000000
Name: points, Length: 8, dtype: float64

In [12]:
reviews.taster_name.describe()

count         103727
unique            19
top       Roger Voss
freq           25514
Name: taster_name, dtype: object

In [13]:
reviews.points.mean()

88.44713820775404

In [14]:
reviews.taster_name.unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams',
       'Christina Pickard'], dtype=object)

In [15]:
reviews.taster_name.value_counts()

Roger Voss           25514
Michael Schachner    15134
                     ...
Fiona Adams             27
Christina Pickard        6
Name: taster_name, Length: 19, dtype: int64

In [16]:
review_points_mean = reviews.points.mean()
reviews.points.map(lambda p: p - review_points_mean)

0        -1.447138
1        -1.447138
            ...
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In [17]:
def remean_points(row):
    row.points = row.points - review_points_mean
    return row
reviews.apply(remean_points, axis='columns')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.447138,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.447138,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,1.552862,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,1.552862,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [18]:
reviews.head(1)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia

In [19]:
review_points_mean = reviews.points.mean()
reviews.points - review_points_mean

0        -1.447138
1        -1.447138
            ...
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In [20]:
reviews.country + " - " + reviews.region_1

0            Italy - Etna
1                     NaN
               ...
129969    France - Alsace
129970    France - Alsace
Length: 129971, dtype: object

# Grouping & Sorting

In [3]:
reviews.groupby('points').points.count()

points
80     397
81     692
      ...
99      33
100     19
Name: points, Length: 21, dtype: int64

In [4]:
reviews.groupby('points').price.min()

points
80      5.0
81      5.0
       ...
99     44.0
100    80.0
Name: price, Length: 21, dtype: float64

In [5]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [6]:
reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

winery
1+1=3                          1+1=3 NV Rosé Sparkling (Cava)
10 Knots                 10 Knots 2010 Viognier (Paso Robles)
                                  ...
àMaurice    àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                         Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

In [8]:
reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()])

                              country  \
country   province
Argentina Mendoza Province  Argentina
          Other             Argentina
...                               ...
Uruguay   San Jose            Uruguay
          Uruguay             Uruguay

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
...                                                                       ...
Uruguay   San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                          designation  points  price  \
country   province
Argentina Mendoza Province           Nicasia Vineyard      97  120.0
          Other                               Reserva      95   90.0
...                                               ...     ...    ...
Uruguay   San Jose           El Preciado Gran Reserva      87   50.0
          Uruguay           Blend 002 Limited Edition      91   22.0

                                    province region_1 region_2  \
country   province
Argentina Mendoza Province  Mendoza Province  Mendoza      NaN
          Other                        Other    Salta      NaN
...                                      ...      ...      ...
Uruguay   San Jose                  San Jose      NaN      NaN
          Uruguay                    Uruguay      NaN      NaN

                                  taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province  Michael Schachner           @wineschach
          Other             Michael Schachner           @wineschach
...                                       ...                   ...
Uruguay   San Jose          Michael Schachner           @wineschach
          Uruguay           Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
...                                                                       ...
Uruguay   San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
...                                           ...                   ...
Uruguay   San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

[425 rows x 13 columns]

In [9]:
reviews.groupby(['country']).price.agg([len, min, max])

              len   min    max
country
Argentina  3800.0   4.0  230.0
Armenia       2.0  14.0   15.0
...           ...   ...    ...
Ukraine      14.0   6.0   13.0
Uruguay     109.0  10.0  130.0

[43 rows x 3 columns]

In [10]:
countries_reviewed = reviews.groupby(['country', 'province']).description.agg([len])
countries_reviewed

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
...                          ...
Uruguay   San Jose             3
          Uruguay             24

[425 rows x 1 columns]

In [11]:
mi = _.index
type(mi)

pandas.core.indexes.multi.MultiIndex

In [12]:
countries_reviewed.reset_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
..         ...               ...   ...
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

In [13]:
countries_reviewed = countries_reviewed.reset_index()
countries_reviewed.sort_values(by='len')

    country               province    len
179  Greece  Muscat of Kefallonian      1
192  Greece          Sterea Ellada      1
..      ...                    ...    ...
415      US             Washington   8639
392      US             California  36247

[425 rows x 3 columns]

In [14]:
countries_reviewed.sort_values(by='len', ascending=False)

    country    province    len
392      US  California  36247
415      US  Washington   8639
..      ...         ...    ...
63    Chile     Coelemu      1
149  Greece      Beotia      1

[425 rows x 3 columns]

In [16]:
countries_reviewed.sort_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
..         ...               ...   ...
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

# Data types and missing data

In [3]:
reviews.price.dtype

dtype('float64')

In [4]:
reviews.dtypes

country        object
description    object
                ...
variety        object
winery         object
Length: 13, dtype: object

In [5]:
reviews.points.astype('float64')

0         87.0
1         87.0
          ...
129969    90.0
129970    90.0
Name: points, Length: 129971, dtype: float64

In [6]:
reviews.index.dtype

dtype('int64')

In [7]:
reviews[reviews.country.isnull()]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
913,NaN,"Amber in color, this wine has aromas of peach ...",Asureti Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2014 Asureti Valley Chinuri,Chinuri,Gotsa Family Wines
3131,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager Red,Red Blend,Barton & Guestier
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129590,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Büyülübağ 2012 Shah Red,Red Blend,Büyülübağ
129900,NaN,This wine offers a delightful bouquet of black...,NaN,91,32.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot

In [8]:
reviews.region_2.fillna("Unknown")

0         Unknown
1         Unknown
           ...
129969    Unknown
129970    Unknown
Name: region_2, Length: 129971, dtype: object

In [9]:
reviews.taster_twitter_handle.replace("@kerinokeefe", "@kerino")

0            @kerino
1         @vossroger
             ...
129969    @vossroger
129970    @vossroger
Name: taster_twitter_handle, Length: 129971, dtype: object

# Renaming and combining

In [10]:
reviews.rename(columns={'points': 'score'})

,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [11]:
reviews.rename(index={0: 'firstEntry', 1: 'secondEntry'})

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
firstEntry,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
secondEntry,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [12]:
reviews.rename_axis("wines", axis='rows').rename_axis("fields", axis='columns')

fields,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
wines,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [2]:
canadian_youtube = pd.read_csv("CAvideos.csv")
british_youtube = pd.read_csv("GBvideos.csv")
pd.concat([canadian_youtube, british_youtube])

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38911,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...
38912,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...
38913,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...
38914,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...
38915,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...

In [3]:
left = canadian_youtube.set_index(['title', 'trending_date'])
right = british_youtube.set_index(['title', 'trending_date'])
left.join(right, lsuffix='_CAN', rsuffix='_UK')

                                                                 video_id_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       PNn8sECd7io
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       DvPW66IFhMI
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       EXEaMjFeiEk
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       bYvQmusLaxw
                                                   17.21.12       bYvQmusLaxw
...                                                                       ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       WttN1Z0XF4k
                                                   18.29.04       WttN1Z0XF4k
                                                   18.30.04       WttN1Z0XF4k
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       Wt9Gkpmbt44
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       Az72jrKbANA

                                                                                channel_title_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                            Markiplier
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                        AlexRamiGaming
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                        AlexRamiGaming
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                  Pure Living for Life
                                                   17.21.12                  Pure Living for Life
...                                                                                           ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                          How Talented
                                                   18.29.04                          How Talented
                                                   18.30.04                          How Talented
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                         TheBigJackpot
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       Right Side Broadcasting Network

                                                                  category_id_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    20
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                    20
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                    20
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                    24
                                                   17.21.12                    24
...                                                                           ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                    24
                                                   18.29.04                    24
                                                   18.30.04                    24
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                    24
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                    25

                                                                          publish_time_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       2018-01-03T19:33:53.000Z
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       2018-03-09T07:15:52.000Z
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       2018-03-10T06:26:17.000Z
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       2017-12-20T02:49:11.000Z
                                                   17.21.12       2017-12-20T02:49:11.000Z
...                                                                                    ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       2018-04-28T19:40:58.000Z
                                                   18.29.04       2018-04-28T19:40:58.000Z
                                                   18.30.04       2018-04-28T19:40:58.000Z
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       2018-05-07T06:58:59.000Z
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       2018-04-03T23:12:37.000Z

                                                                                                           tags_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       getting over it|"markiplier"|"funny moments"|"...
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       PS4 Battle Royale|"PS4 Pro Battle Royale"|"Bat...
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       PS4 Battle Royale|"PS4 Pro Battle Royale"|"Bat...
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       timber frame|"timber framing"|"timber frame ra...
                                                   17.21.12       timber frame|"timber framing"|"timber frame ra...
...                                                                                                             ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       bgt|"bgt 2018"|"britain got talent"|"britain´s...
                                                   18.29.04       bgt|"bgt 2018"|"britain got talent"|"britain´s...
                                                   18.30.04       bgt|"bgt 2018"|"britain got talent"|"britain´s...
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       Slot Machine|"win"|"Gambling"|"Big Win"|"raja"...
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       YouTube shooter|"YouTube active shooter"|"acti...

                                                                  views_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01          835930
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03          212838
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03          200764
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12           79152
                                                   17.21.12          232762
...                                                                     ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05          713400
                                                   18.29.04          231906
                                                   18.30.04          476253
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05           28973
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04          103513

                                                                  likes_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01           47058
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            5199
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            5620
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            7761
                                                   17.21.12           15515
...                                                                     ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05            4684
                                                   18.29.04            1924
                                                   18.30.04            3417
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05            2167
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04            1722

                                                                  dislikes_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01               1023
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                542
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                537
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                159
                                                   17.21.12                329
...                                                                        ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                260
                                                   18.29.04                 78
                                                   18.30.04                176
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                175
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                181

                                                                  comment_count_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    8250
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                      11
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                      45
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                    1965
                                                   17.21.12                    3601
...                                                                             ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                     266
                                                   18.29.04                     146
                                                   18.30.04                     240
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                      10
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                      76

                                                                                              thumbnail_link_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       https://i.ytimg.com/vi/PNn8sECd7io/default.jpg
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       https://i.ytimg.com/vi/DvPW66IFhMI/default.jpg
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       https://i.ytimg.com/vi/EXEaMjFeiEk/default.jpg
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       https://i.ytimg.com/vi/bYvQmusLaxw/default.jpg
                                                   17.21.12       https://i.ytimg.com/vi/bYvQmusLaxw/default.jpg
...                                                                                                          ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       https://i.ytimg.com/vi/WttN1Z0XF4k/default.jpg
                                                   18.29.04       https://i.ytimg.com/vi/WttN1Z0XF4k/default.jpg
                                                   18.30.04       https://i.ytimg.com/vi/WttN1Z0XF4k/default.jpg
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       https://i.ytimg.com/vi/Wt9Gkpmbt44/default.jpg
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       https://i.ytimg.com/vi/Az72jrKbANA/default.jpg

                                                                  ...  \
title                                              trending_date  ...
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       ...
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       ...
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       ...
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       ...
                                                   17.21.12       ...
...                                                               ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       ...
                                                   18.29.04       ...
                                                   18.30.04       ...
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       ...
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       ...

                                                                  tags_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01           NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03           NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03           NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12           NaN
                                                   17.21.12           NaN
...                                                                   ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05           NaN
                                                   18.29.04           NaN
                                                   18.30.04           NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05           NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04           NaN

                                                                  views_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01            NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            NaN
                                                   17.21.12            NaN
...                                                                    ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05            NaN
                                                   18.29.04            NaN
                                                   18.30.04            NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05            NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04            NaN

                                                                  likes_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01            NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            NaN
                                                   17.21.12            NaN
...                                                                    ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05            NaN
                                                   18.29.04            NaN
                                                   18.30.04            NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05            NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04            NaN

                                                                 dislikes_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01              NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03              NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03              NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12              NaN
                                                   17.21.12              NaN
...                                                                      ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05              NaN
                                                   18.29.04              NaN
                                                   18.30.04              NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05              NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04              NaN

                                                                 comment_count_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                   NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                   NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                   NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                   NaN
                                                   17.21.12                   NaN
...                                                                           ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                   NaN
                                                   18.29.04                   NaN
                                                   18.30.04                   NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                   NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                   NaN

                                                                 thumbnail_link_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                    NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                    NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                    NaN
                                                   17.21.12                    NaN
...                                                                            ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                    NaN
                                                   18.29.04                    NaN
                                                   18.30.04                    NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                    NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                    NaN

                                                                  comments_disabled_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                        NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                        NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                        NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                        NaN
                                                   17.21.12                        NaN
...                                                                                ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                        NaN
                                                   18.29.04                        NaN
                                                   18.30.04                        NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                        NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                        NaN

                                                                 ratings_disabled_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                      NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                      NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                      NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                      NaN

# End